### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by HaimBendanan** [Unity-Technologies/GenericRecorder-MovieRecorderPlugin#1]
Hey,

I am getting a build error:

_Assets/GenericRecorder-MovieRecorderPlugin/source/Recorder/Engine/MediaRecorder.cs(9,19): error CS0234: The type or namespace name `Media' does not exist in the namespace `UnityEditor'. Are you missing an assembly reference?_

Do you know how can i fix this? I added the GenericFramRecorder source also. I am running unity 2017.1, tried with 2017.2, still no luck.

**Comment by HaimBendanan** [comment]
@jasonm-unity could you help me here? I am really busy on schedule and this could be a life saver. Can you contact me asap? haimbendanan@gmail.com

**Comment by jasonm-unity** [comment]
simple: DO NOT clone/fetch the code from Github, but from one of the latest releases and download the Package, not the source. the source is intended only is you whish to extend the system.

for example: https://github.com/Unity-Technologies/GenericFrameRecorder/releases/tag/2107-09-01
click on Recorder.unitypackage  not on Source code (zip) .

once you have the package, simply import it into unity.

the recorder window will be available under the menu item: Tools.

enjoy and please report any issues back here...

**Comment by HaimBendanan** [comment]
Hey!!

Ok good to know, does it include the movie recorder code?
https://github.com/Unity-Technologies/GenericRecorder-MovieRecorderPlugin

**Comment by HaimBendanan** [comment]
ok got it!
well this is awesome that you are focusing on this. for now it wont be
relevant for me for two reasons: I need to record mp4 with sound and in
iOS. i will wait to see the progress with this feature, this is great!

Thanks

**Comment by jasonm-unity** [comment]
yes and no.
The movie recorder requires a version of unity that will only come out next year.
But, the package does contain an MP4 recorder, but does not support sound.

iOS mp4 recording with sound is quite a ways off actually. As of today, it's geared it desktops...
